# See https://pre-commit.com/
# See https://github.com/python/black#version-control-integration
repos:
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
